/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIS;

import Model.GameController;


/**
 *
 * @author Carlos Cabrera
 */
public class Combat extends javax.swing.JPanel {

  
    private MainFrame parent;
    private GameController controller;
    
    public Combat(MainFrame parent, GameController controller) {
        this.parent = parent;
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        redJComboBox1 = new javax.swing.JComboBox<>();
        redJComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        redJComboBox3 = new javax.swing.JComboBox<>();
        redJComboBox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        blueJComboBox1 = new javax.swing.JComboBox<>();
        blueJComboBox2 = new javax.swing.JComboBox<>();
        blueJComboBox3 = new javax.swing.JComboBox<>();
        blueJComboBox4 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        resultLabel = new javax.swing.JLabel();

        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Ejercito Rojo");

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Ejercito Azúl");

        jLabel3.setText("Unidades");

        jLabel4.setText("Unidades");

        jLabel5.setText("1");

        redJComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantry", "Archers", "Spears", "Cavalry" }));

        redJComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantry", "Archers", "Spears", "Cavalry" }));

        jLabel6.setText("2");

        redJComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantry", "Archers", "Spears", "Cavalry" }));

        redJComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantry", "Archers", "Spears", "Cavalry" }));

        jLabel7.setText("3");

        jLabel8.setText("4");

        blueJComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantry", "Archers", "Spears", "Cavalry" }));
        blueJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueJComboBox1ActionPerformed(evt);
            }
        });

        blueJComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantry", "Archers", "Spears", "Cavalry" }));
        blueJComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueJComboBox2ActionPerformed(evt);
            }
        });

        blueJComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantry", "Archers", "Spears", "Cavalry" }));
        blueJComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueJComboBox3ActionPerformed(evt);
            }
        });

        blueJComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantry", "Archers", "Spears", "Cavalry" }));
        blueJComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueJComboBox4ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("PELEAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        resultLabel.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(redJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blueJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redJComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redJComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(redJComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resultLabel)
                                    .addComponent(jToggleButton1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blueJComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueJComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueJComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(redJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redJComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(blueJComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redJComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(blueJComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redJComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(blueJComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(resultLabel)
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void blueJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueJComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueJComboBox1ActionPerformed

    private void blueJComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueJComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueJComboBox2ActionPerformed

    private void blueJComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueJComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueJComboBox3ActionPerformed

    private void blueJComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueJComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueJComboBox4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String[] blueArmy = {(String) blueJComboBox1.getSelectedItem(), (String) blueJComboBox2.getSelectedItem(),
                (String) blueJComboBox3.getSelectedItem(), (String) blueJComboBox4.getSelectedItem()};

        String[] redArmy = {(String) redJComboBox1.getSelectedItem(), (String) redJComboBox2.getSelectedItem(),
                (String) redJComboBox3.getSelectedItem(), (String) redJComboBox4.getSelectedItem()};

        controller.setArmies(5, controller.parseArmyFromStrings(blueArmy), controller.parseArmyFromStrings(redArmy));

        if (controller.combat()) {
            resultLabel.setText("Azul gana");
        }
        else {
            resultLabel.setText("Rojo gana");
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> blueJComboBox1;
    private javax.swing.JComboBox<String> blueJComboBox2;
    private javax.swing.JComboBox<String> blueJComboBox3;
    private javax.swing.JComboBox<String> blueJComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> redJComboBox1;
    private javax.swing.JComboBox<String> redJComboBox2;
    private javax.swing.JComboBox<String> redJComboBox3;
    private javax.swing.JComboBox<String> redJComboBox4;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
